DjangoExerciseTwo/DjangoExerciseTwo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
import userInfo.views as views


urlpatterns = [
    url(r'^$',views.index,name='index'),
    #url(r'^users/', views.users,name='user'),
    url(r'^user_db/',include('userInfo.urls')),
    #url(r'^forms/',views.form_name_view,name='form_name'),
    path('admin/', admin.site.urls),
]

DjangoExerciseTwo/userInfo/urls.py
from django.conf.urls import url
from userInfo import views

app_name = "userInfo"

urlpatterns = [
    url(r'^$',views.users,name='users'),
    url(r'^forms/$', views.form_name_view, name='forms'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),

    url(r'^register/$', views.register_view, name='register'),

    #url(r'users/$',views.users,name='user'),


]

DjangoExerciseTwo/userInfo/models.py
from django.db import models
from django.contrib.auth.models import User as User_default
# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=264,blank=True)
    last_name = models.CharField(max_length=264, blank=True)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.first_name

class UserProfile(models.Model):
    user = models.OneToOneField(User_default,on_delete=models.CASCADE)

    #additional

    porfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.username

DjangoExerciseTwo/userInfo/forms.py
from django import forms
from django.core import validators
from userInfo.models import User
from userInfo.models import UserProfile
from django.contrib.auth.models import User as User_default



class login_Form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User_default
        fields = ('username','email','password')

class UserProfile_Form(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('porfolio_site','profile_pic')


class model_Form(forms.ModelForm):

    class Meta:
        model = User
        fields = "__all__"


    def save_user_form(self):
        all_clean_data = super().clean()
        fname = all_clean_data['first_name']
        lname = all_clean_data['last_name']
        email = all_clean_data['email']

        if len(fname)==0 or len(lname)==0 or len(email)==0:
            print("Make sure all fields are filled!")
        else:
            #t = User.objects.get_or_create(first_name=fname,last_name=lname,email=email)[0]
            #t.save()
            return True


# check if the first letter of name is z or not
def check_for_z(value):
    if value[0].lower() != "z":
        raise forms.ValidationError("Name needs to start with z")


class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])

    email = forms.EmailField()

    # check the email
    verify_email = forms.EmailField(label="Enter your Email again")
    text = forms.CharField(widget=forms.Textarea)


    # clean the form
    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("Make sure emails match!")
    # botcatcher
    botcatcher = forms.CharField(required= False,widget=forms.HiddenInput,validators=[validators.MaxValueValidator(0)])

    def clean_botcatcher(self):
        botcatcher = self.cleaned_data['botcatcher']
        if len(botcatcher) > 0:
            raise forms.ValidationError("GOTCHA BOT!")
        return botcatcher

DjangoExerciseTwo/userInfo/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from userInfo.models import User
from django.contrib.auth.models import User as User_default

from . import forms

#for login
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
#from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    index_dict = {'insert_index':"Go to /users to see the list of user information, /forms to fill the form"}
    return render(request,'userInfo/index.html',context=index_dict)

def users(request):
    user_list = User_default.objects.all()
    user_dict = {'users_records':user_list}
    return render(request,'userInfo/user.html',context=user_dict)

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("Your are logged in!")

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)# check the login info for you

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'userInfo/login.html', {})


def register_view(request):
    registered = False
    if request.method == "POST":

        login_form = forms.login_Form(data=request.POST)
        UserProfile_Form = forms.UserProfile_Form(data=request.POST)

        if login_form.is_valid() and UserProfile_Form.is_valid():
            user = login_form.save()
            user.set_password(user.password)
            user.save()

            profile = UserProfile_Form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(login_form.errors,UserProfile_Form.errors)

    else:
        login_form = forms.login_Form()
        UserProfile_Form = forms.UserProfile_Form()

    return render(request,'userInfo/registration.html',{'login_form':login_form,'UserProfile_Form':UserProfile_Form,'registered':registered})

def form_name_view(request):
    form = forms.model_Form()

    if request.method == "POST":
        form = forms.model_Form(request.POST)

        if form.is_valid():
            if form.save_user_form():
                print("VALIDATION SUCCESS and save into models!")
                print("First Name:",form.cleaned_data['first_name'])
                print("Last Name:",form.cleaned_data['last_name'])
                print("Email:",form.cleaned_data['email'])
                form.save(commit=True)
                return users(request)

            #print("TEXT:",form.cleaned_data['text'])


    return render(request,'userInfo/form_page.html',{'form':form})

DjangoExerciseTwo/templates/userInfo/base.html
<!DOCTYPE html>
{% load static%}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "/css/master.css" %}"/>
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index'%}">Home Page</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'userInfo:forms'%}">Fill the Form</a></li>
            <li><a class="navbar-link" href="{% url 'userInfo:users'%}">User List</a></li>
            <li><a class="navbar-link" href="{% url 'userInfo:logout'%}">Logout</a></li>
          {% else %}
          <li><a class="navbar-link" href="{% url 'userInfo:register'%}">Register</a></li>
          <li><a class="navbar-link" href="{% url 'userInfo:login'%}">Login</a></li>
          {% endif %}
        </ul>

      </div>

    </nav>
    <div class="container">

      {%block body_block%}
      <!-- anything outside of this will be ingerited if you extend -->
      {%endblock%}

    </div>

  </body>
</html>

DjangoExerciseTwo/templates/userInfo/form_page.html
<!DOCTYPE html>
<!-- extend from base.html -->
{% extends "userInfo/base.html"%}

  {% block body_block %}

    <h1>Fill out the form!</h1>
      <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">

      </form>
  {% endblock %}

DjangoExerciseTwo/templates/userInfo/index.html
<!DOCTYPE html>
<!-- extend from base.html -->
{% extends "userInfo/base.html"%}

  {% block body_block %}
  <div class="jumbotron">

    <h1>Welcome</h1>
    <!-- template filter: title -->
    <h3>
    {{insert_index|title}} --using title
    </h3>
    <h3>
    {{insert_index|cut:"users"}} --using cut
    </h3>
  </div>

  {% endblock %}

DjangoExerciseTwo/templates/userInfo/login.html
<!DOCTYPE html>
<!-- extend from base.html -->
{% extends "userInfo/base.html"%}

  {% block body_block %}
      <div class="jumbotron">
        <h1>Please Login</h1>
        <form  action="{% url 'userInfo:login'%}" method="post">
          {% csrf_token %}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Enter Username">

          <label for="password">Password:</label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">
        </form>


      </div>


  {% endblock %}

DjangoExerciseTwo/templates/userInfo/registration.html
<!DOCTYPE html>
<!-- extend from base.html -->
{% extends "userInfo/base.html"%}

  {% block body_block %}
    <div class="jumbotron">
      {% if registered %}
        <h1>Thanks for registration!</h1>
      {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>
        <form enctype="multipart/form-data"method="post">
          {% csrf_token %}
          {{ login_form.as_p }}
          {{UserProfile_Form.as_p }}
          <input type="submit" name="" value="Register">

        </form>
      {% endif %}

    </div>



  {% endblock %}

DjangoExerciseTwo/templates/userInfo/user.html
<!DOCTYPE html>
<!-- extend from base.html -->
{% extends "userInfo/base.html"%}

  {% block body_block %}
  <div class="jumbotron">

    <h1 class=" text-center">This is User list. </h1>
    <footer class="blockquote-footer text-center">From Jerry<cite title="Source Title"> Fake Data</cite></footer>
    <!-- <h2>
    <a href="{% url 'userInfo:forms'%}"> Click here to add more users</a>
    </h2>
    <h2>
    <a href="{% url 'admin:index'%}"> Click here to Admin</a>
    </h2>
    <h2>
    <a href="{% url 'index'%}"> Click here to Home Page</a>
    </h2> -->
    <h2 >Here are the User List:</h2>
    {% if users_records %}
    <ol>
      {% for user in users_records %}

          <li>User Info:</li>
          <ul>
            <li>First Name: {{user.username}}</li>
            <li>Last Name: {{user.last_name}}</li>
            <li>Email: {{user.email}}</li>
          </ul>

      {% endfor %}
      </ol>
      {% else %}
      <p>No User Data FOUND!</p>
      {% endif%}


      </div>
      {% endblock %}